"use client";
import { useEffect, useRef, useState } from "react";

function Icon({ name, size = 20 }: { name: "spark" | "settings" | "mic" | "send" | "home" | "heart" | "menu" | "volume"; size?: number }) {
  const paths: Record<string, React.ReactNode> = {
    spark: <><path d="m12 2 1.7 6.3L20 10l-6.3 1.7L12 18l-1.7-6.3L4 10l6.3-1.7L12 2Z"/><path d="m19 16 .6 2.4L22 19l-2.4.6L19 22l-.6-2.4L16 19l2.4-.6L19 16Z"/></>,
    settings: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-1.7 1.7-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6V20h-2.4v-.1a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L8 17l.1-.1a1.7 1.7 0 0 0 .3-1.9 1.7 1.7 0 0 0-1.6-1H6v-2.4h.8a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L8 8.6l1.7-1.7.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.6V5H15v.7a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1 1.7 1.7-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.1V14h-.1a1.7 1.7 0 0 0-1.5 1Z"/></>,
    mic: <><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3M9 21h6"/></>,
    send: <path d="m22 2-7 20-4-9-9-4 20-7ZM22 2 11 13"/>,
    home: <path d="m3 11 9-8 9 8v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1v-9Z"/>,
    heart: <path d="M20.8 8.8c0 5.4-8.8 10.2-8.8 10.2S3.2 14.2 3.2 8.8A4.8 4.8 0 0 1 12 6.2a4.8 4.8 0 0 1 8.8 2.6Z"/>,
    menu: <><path d="M4 6h16M4 12h16M4 18h16"/></>, volume: <><path d="M4 10v4h4l5 4V6l-5 4H4Z"/><path d="M16 9a4 4 0 0 1 0 6M18.5 6.5a8 8 0 0 1 0 11"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

export default function Home() {
  const canvasRef = useRef<HTMLCanvasElement>(null); const [modelState, setModelState] = useState("กำลังโหลด Yuino"); const [message, setMessage] = useState("");
  const [messages, setMessages] = useState([{ from: "yuino", text: "สวัสดีค่ะ ฉันคือ Yuino วันนี้อยากให้ช่วยทำอะไรคะ?" }]);
  useEffect(() => { let app: any; let disposed = false; (async () => { try { const PIXI = await import("pixi.js"); const { Live2DModel } = await import("pixi-live2d-display/cubism4"); (window as any).PIXI = PIXI; (Live2DModel as any).registerTicker(PIXI.Ticker); app = new PIXI.Application({ view: canvasRef.current!, resizeTo: canvasRef.current!.parentElement!, backgroundAlpha: 0, antialias: true }); const model = await Live2DModel.from("/live2d/yuino/Yuino.model3.json"); if (disposed) return; model.anchor.set(.5, 1); model.x = app.screen.width / 2; model.y = app.screen.height * .99; model.scale.set(Math.min(app.screen.width / model.width, app.screen.height / model.height) * 1.05); app.stage.addChild(model); setModelState("Yuino พร้อมคุยแล้ว"); } catch (error) { console.error(error); setModelState("โหลดโมเดลไม่สำเร็จ"); } })(); return () => { disposed = true; app?.destroy(true, { children: true }); }; }, []);
  async function sendMessage() { const text = message.trim(); if (!text) return; const next = [...messages, { from: "me", text }]; setMessages(next); setMessage(""); try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: next.map((item) => ({ role: item.from === "me" ? "user" : "assistant", content: item.text })) }) }); const data = await response.json(); setMessages((current) => [...current, { from: "yuino", text: data.text ?? "ระบบยังไม่พร้อมค่ะ" }]); } catch { setMessages((current) => [...current, { from: "yuino", text: "เชื่อมต่อไม่สำเร็จ ลองใหม่อีกครั้งนะคะ" }]); } }
  return <main className="fullscreen-shell"><section className="full-model"><div className="ambient ambient-a"/><div className="ambient ambient-b"/><div className="model-stage"><canvas ref={canvasRef}/></div><header className="overlay topbar"><div className="brand"><span className="brand-icon"><Icon name="spark" size={18}/></span><span>YUINO</span></div><div className="model-status"><i/>{modelState}</div><button className="glass-icon" aria-label="ตั้งค่า"><Icon name="settings"/></button></header><div className="overlay identity"><span className="eyebrow">YOUR AI COMPANION</span><strong>Yuino</strong><span>อยู่ตรงนี้เสมอ</span></div><div className="overlay model-tools"><button className="round-glass" aria-label="เปิดเสียง"><Icon name="volume"/></button><button className="round-glass" aria-label="ตั้งค่าโมเดล"><Icon name="settings"/></button></div></section><section className="chat-dock"><div className="chat-head"><div><span className="eyebrow">CONVERSATION</span><h1>คุยกับ Yuino</h1></div><span className="live-badge"><i/>LIVE</span></div><div className="messages">{messages.slice(-3).map((item,index)=><div key={index} className={`bubble-row ${item.from === "me" ? "mine" : ""}`}><div className="bubble">{item.text}</div></div>)}</div><div className="composer"><button className="mic-button" aria-label="พูดด้วยเสียง"><Icon name="mic" size={19}/></button><input value={message} onChange={(event)=>setMessage(event.target.value)} onKeyDown={(event)=>event.key === "Enter" && sendMessage()} placeholder="พิมพ์ข้อความถึง Yuino..."/><button className="send-button" onClick={sendMessage} aria-label="ส่งข้อความ"><Icon name="send" size={18}/></button></div></section><nav className="bottom-nav"><button className="active"><Icon name="home"/><span>หน้าหลัก</span></button><button><Icon name="heart"/><span>ความทรงจำ</span></button><button><Icon name="menu"/><span>เมนู</span></button></nav></main>;
}
