"use client";
import { useEffect, useRef, useState } from "react";

export default function Home() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [modelState, setModelState] = useState("กำลังโหลด Yuino...");
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState([{ from: "yuino", text: "สวัสดีค่ะ ฉันคือ Yuino ✨ วันนี้อยากให้ช่วยทำอะไรคะ?" }]);
  useEffect(() => { let app: any; let disposed = false; (async () => { try { const PIXI = await import("pixi.js"); const { Live2DModel } = await import("pixi-live2d-display"); (window as any).PIXI = PIXI; Live2DModel.registerTicker(PIXI.Ticker); app = new PIXI.Application({ view: canvasRef.current!, resizeTo: canvasRef.current!.parentElement!, backgroundAlpha: 0, antialias: true }); const model = await Live2DModel.from("/live2d/yuino/Yuino.model3.json"); if (disposed) return; model.anchor.set(.5, 1); model.x = app.screen.width / 2; model.y = app.screen.height * .98; model.scale.set(Math.min(app.screen.width / model.width, app.screen.height / model.height) * .82); app.stage.addChild(model); setModelState("Yuino พร้อมคุยแล้ว"); } catch (error) { console.error(error); setModelState("โหลดโมเดลไม่สำเร็จ"); } })(); return () => { disposed = true; app?.destroy(true, { children: true }); }; }, []);
  async function sendMessage() { const trimmed = message.trim(); if (!trimmed) return; const next = [...messages, { from: "me", text: trimmed }]; setMessages(next); setMessage(""); try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: next.map((item) => ({ role: item.from === "me" ? "user" : "assistant", content: item.text })) }) }); const data = await response.json(); setMessages((current) => [...current, { from: "yuino", text: data.text ?? `ขอโทษนะคะ ${data.error ?? "ระบบยังไม่พร้อม"}` }]); } catch { setMessages((current) => [...current, { from: "yuino", text: "เชื่อมต่อไม่สำเร็จ ลองใหม่อีกครั้งนะคะ" }]); } }
  return <main className="waifu-shell"><header className="topbar"><div className="brand"><span className="brand-mark">✦</span><span>YUINO</span></div><div className="status"><span className="status-dot" />{modelState}</div><button className="icon-button" aria-label="ตั้งค่า">⚙</button></header><section className="stage-card"><div className="glow glow-one" /><div className="glow glow-two" /><div className="model-stage"><canvas ref={canvasRef} /></div><div className="mood-pill">☀ อารมณ์ดี <span>•</span> พร้อมคุย</div><div className="stage-caption"><strong>Yuino</strong><span>AI companion ของคุณ</span></div></section><section className="chat-panel"><div className="chat-heading"><div><span className="eyebrow">CONVERSATION</span><h1>คุยกับ Yuino</h1></div><span className="live-badge">LIVE</span></div><div className="messages">{messages.map((item, index) => <div key={index} className={`bubble-row ${item.from === "me" ? "mine" : ""}`}><div className="bubble">{item.text}</div></div>)}</div><div className="composer"><input value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => event.key === "Enter" && sendMessage()} placeholder="พิมพ์ข้อความถึง Yuino..." /><button className="mic-button" aria-label="พูดด้วยเสียง">◉</button><button className="send-button" onClick={sendMessage} aria-label="ส่งข้อความ">↑</button></div></section><nav className="bottom-nav"><button className="active">⌂<span>หน้าหลัก</span></button><button>♡<span>ความทรงจำ</span></button><button>☷<span>ตั้งค่า</span></button></nav></main>;
}
