create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_key text not null default 'default',
  title text not null default 'Vivian conversation',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  user_key text not null default 'default',
  memory text not null,
  category text not null default 'general',
  importance smallint not null default 3 check (importance between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_key, memory)
);

create index if not exists messages_conversation_created_idx on public.messages(conversation_id, created_at);
create index if not exists memories_user_importance_idx on public.memories(user_key, importance desc, updated_at desc);

alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.memories enable row level security;
